/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

/**
 *
 * @author Usuario
 */
public class MostrarProductos extends javax.swing.JFrame {
    
    
    ProductTester tester = ProductTester.getAdm();
    public MostrarProductos() {
        initComponents();
        setSize(748, 443);
        setLocationRelativeTo(null);
        setResizable(false);
        tester.MostraProductos(textarea);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btn_cerrar2 = new javax.swing.JButton();
        btn_minimizar = new javax.swing.JButton();
        lbl_inventario = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textarea = new javax.swing.JTextArea();
        lbl_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_cerrar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_cancel_40px.png"))); // NOI18N
        btn_cerrar2.setBorder(null);
        btn_cerrar2.setBorderPainted(false);
        btn_cerrar2.setContentAreaFilled(false);
        btn_cerrar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cerrar2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_cancel_50px.png"))); // NOI18N
        btn_cerrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrar2ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_cerrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 0, 40, 40));

        btn_minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_macos_minimize_40px.png"))); // NOI18N
        btn_minimizar.setBorder(null);
        btn_minimizar.setBorderPainted(false);
        btn_minimizar.setContentAreaFilled(false);
        btn_minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_minimizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_macos_minimize_50px.png"))); // NOI18N
        btn_minimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_minimizarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 40, 40));

        lbl_inventario.setBackground(new java.awt.Color(255, 255, 255));
        lbl_inventario.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_inventario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_inventario.setText("Productos ingresados");
        jPanel3.add(lbl_inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 230, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 40));

        textarea.setColumns(20);
        textarea.setRows(5);
        jScrollPane2.setViewportView(textarea);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 390, 280));

        lbl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img1.jpeg"))); // NOI18N
        getContentPane().add(lbl_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 443));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cerrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrar2ActionPerformed
        IngresarSistema sistema = new IngresarSistema();
        sistema.setVisible(true);
        this.setVisible(false);                
    }//GEN-LAST:event_btn_cerrar2ActionPerformed

    private void btn_minimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_minimizarActionPerformed
        this.setState(ICONIFIED);
    }//GEN-LAST:event_btn_minimizarActionPerformed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        int xx = evt.getXOnScreen();
        int xy = evt.getYOnScreen();

        this.setLocation(xx - x, xy - y);
    }//GEN-LAST:event_jPanel3MouseDragged
    
    int x,y;
    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel3MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cerrar2;
    private javax.swing.JButton btn_minimizar;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_fondo;
    private javax.swing.JLabel lbl_inventario;
    private javax.swing.JTextArea textarea;
    // End of variables declaration//GEN-END:variables
}
